import ReduxProvider from "@/redux/redux-provider/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>

      <div>{children}</div>
    </ReduxProvider>
  )
}
